% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

% By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

:- dynamic(found/1).

fib(0,0) :- !.
fib(1,1) :- !.
fib(N,F) :- found(fib(N,F)),!.          % Query for found result
fib(N,F) :- N2 is N-2, fib(N2,F2),      % Importance performance gain from placing the former first.
	    N1 is N-1, fib(N1,F1),
	    F is F1 + F2,               % Defn of Fib(n)
	    assert(found(fib(N,F))).

% Functional-y soln
sumEvenBelow(X,Y) :- findall(F, ( between(0,X,N), fib(N,F)), List  ),  % List comprehension
		     include( even, List, List1  ),                    % Filter
		     foldl( plus, List1, 0, Y).                        % Sum the list

even(X) :- 0 is mod(X,2).

flush :- retractall(found(fib(_,_))).
